# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.0.0+mc1.21.11
group=schematic.tiling

# Dependencies
fabric_api_version=0.141.6+1.21.11
malilib_version=loabWpyU
litematica_version=mengBR9D
